### Obtener todos
GET http://localhost:8080/api/users

### Obtener por id
GET http://localhost:8080/api/users/1

### Crear
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "Carlos",
  "phone": "121212",
  "email": "carlos@email.com",
  "password": "12345678",
  "photoUrl": "",
  "dateBirth": "2000-08-22",
  "role": "USER"
}

### Editar
PUT http://localhost:8080/api/users/1
Content-Type: application/json

{
  "name": "Carlos",
  "phone": "333333",
  "photoUrl": "foto",
  "dateBirth": "2000-08-22",
  "role": "USER"
}

### Eliminar
DELETE http://localhost:8080/api/users/1
